version: "3"
services:

  redis:
    image: redis
  db:
    image: postgres
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  vote:
    image: dockersamples/vote
    ports:
      - 5000:80
    depends_on:
      - redis
      - db

  result:
    image: dockersamples/result
    ports:
      - 5001:80
      

  worker:
    image: dockersamples/worker
